"""Permission and role definitions.

Permissions are expressed as strings so they stay readable in the database,
audit logs, and API errors, e.g. ``patient.read``.

New permissions are added here and in ``ROLE_PERMISSIONS``. Authorization is
never hardcoded across routes - routes depend on these reusable constants.
"""

from app.models.enums import UserRole

# ---------------------------------------------------------------------------
# Permission catalog
# ---------------------------------------------------------------------------
PERMISSION_ORGANIZATIONS_READ = "organization.read"

PERMISSION_USERS_READ = "user.read"
PERMISSION_USERS_CREATE = "user.create"
PERMISSION_USERS_UPDATE = "user.update"

PERMISSION_PATIENT_READ = "patient.read"
PERMISSION_PATIENT_CREATE = "patient.create"
PERMISSION_PATIENT_UPDATE = "patient.update"

PERMISSION_CAREGIVER_READ = "caregiver.read"
PERMISSION_CAREGIVER_CREATE = "caregiver.create"
PERMISSION_CAREGIVER_UPDATE = "caregiver.update"

PERMISSION_CARE_TEAM_READ = "care_team.read"
PERMISSION_CARE_TEAM_UPDATE = "care_team.update"

PERMISSION_OBSERVATION_READ = "observation.read"
PERMISSION_OBSERVATION_CREATE = "observation.create"
PERMISSION_OBSERVATION_UPDATE = "observation.update"

PERMISSION_VISIT_READ = "visit.read"
PERMISSION_VISIT_CREATE = "visit.create"
PERMISSION_VISIT_UPDATE = "visit.update"

PERMISSION_CARE_TASK_READ = "care_task.read"
PERMISSION_CARE_TASK_CREATE = "care_task.create"
PERMISSION_CARE_TASK_ASSIGN = "care_task.assign"
PERMISSION_CARE_TASK_UPDATE = "care_task.update"

PERMISSION_CARE_PLAN_READ = "care_plan.read"
PERMISSION_CARE_PLAN_CREATE = "care_plan.create"
PERMISSION_CARE_PLAN_UPDATE = "care_plan.update"

PERMISSION_CARE_GOAL_READ = "care_goal.read"
PERMISSION_CARE_GOAL_CREATE = "care_goal.create"
PERMISSION_CARE_GOAL_UPDATE = "care_goal.update"

PERMISSION_ALERT_READ = "alert.read"
PERMISSION_ALERT_UPDATE = "alert.update"

PERMISSION_COMMUNICATION_READ = "communication.read"
PERMISSION_COMMUNICATION_CREATE = "communication.create"

PERMISSION_ATTACHMENT_READ = "attachment.read"
PERMISSION_ATTACHMENT_CREATE = "attachment.create"

PERMISSION_CONSENT_READ = "consent.read"
PERMISSION_CONSENT_CREATE = "consent.create"
PERMISSION_CONSENT_UPDATE = "consent.update"

PERMISSION_AUDIT_READ = "audit.read"

PERMISSION_CAREGIVER_REPORT_READ = "caregiver_report.read"
PERMISSION_CAREGIVER_REPORT_CREATE = "caregiver_report.create"
PERMISSION_CAREGIVER_REPORT_CONFIRM = "caregiver_report.confirm"

# Convenience constants used by routes.
ALL_PERMISSIONS = frozenset(
    {
        PERMISSION_ORGANIZATIONS_READ,
        PERMISSION_USERS_READ,
        PERMISSION_USERS_CREATE,
        PERMISSION_USERS_UPDATE,
        PERMISSION_PATIENT_READ,
        PERMISSION_PATIENT_CREATE,
        PERMISSION_PATIENT_UPDATE,
        PERMISSION_CAREGIVER_READ,
        PERMISSION_CAREGIVER_CREATE,
        PERMISSION_CAREGIVER_UPDATE,
        PERMISSION_CARE_TEAM_READ,
        PERMISSION_CARE_TEAM_UPDATE,
        PERMISSION_OBSERVATION_READ,
        PERMISSION_OBSERVATION_CREATE,
        PERMISSION_OBSERVATION_UPDATE,
        PERMISSION_VISIT_READ,
        PERMISSION_VISIT_CREATE,
        PERMISSION_VISIT_UPDATE,
        PERMISSION_CARE_TASK_READ,
        PERMISSION_CARE_TASK_CREATE,
        PERMISSION_CARE_TASK_ASSIGN,
        PERMISSION_CARE_TASK_UPDATE,
        PERMISSION_CARE_PLAN_READ,
        PERMISSION_CARE_PLAN_CREATE,
        PERMISSION_CARE_PLAN_UPDATE,
        PERMISSION_CARE_GOAL_READ,
        PERMISSION_CARE_GOAL_CREATE,
        PERMISSION_CARE_GOAL_UPDATE,
        PERMISSION_ALERT_READ,
        PERMISSION_ALERT_UPDATE,
        PERMISSION_COMMUNICATION_READ,
        PERMISSION_COMMUNICATION_CREATE,
        PERMISSION_ATTACHMENT_READ,
        PERMISSION_ATTACHMENT_CREATE,
        PERMISSION_CONSENT_READ,
        PERMISSION_CONSENT_CREATE,
        PERMISSION_CONSENT_UPDATE,
        PERMISSION_AUDIT_READ,
        PERMISSION_CAREGIVER_REPORT_READ,
        PERMISSION_CAREGIVER_REPORT_CREATE,
        PERMISSION_CAREGIVER_REPORT_CONFIRM,
    }
)


# ---------------------------------------------------------------------------
# Role -> permission mapping
# ---------------------------------------------------------------------------
# Staff roles (ADMIN, CARE_COORDINATOR, NURSE, DOCTOR) operate org-wide.
# CAREGIVER and PATIENT are object-scoped by app/services/authorization.py.
_PATIENT_SCOPED_READS = frozenset(
    {
        PERMISSION_PATIENT_READ,
        PERMISSION_OBSERVATION_READ,
        PERMISSION_VISIT_READ,
        PERMISSION_CARE_TASK_READ,
        PERMISSION_CARE_PLAN_READ,
        PERMISSION_CARE_GOAL_READ,
        PERMISSION_CARE_TEAM_READ,
        PERMISSION_ALERT_READ,
        PERMISSION_COMMUNICATION_READ,
        PERMISSION_CONSENT_READ,
        PERMISSION_ATTACHMENT_READ,
        PERMISSION_CAREGIVER_REPORT_READ,
    }
)

PATIENT_PERMISSIONS = _PATIENT_SCOPED_READS | frozenset(
    {
        PERMISSION_OBSERVATION_CREATE,
    }
)

CAREGIVER_PERMISSIONS = _PATIENT_SCOPED_READS | frozenset(
    {
        PERMISSION_CAREGIVER_REPORT_CREATE,
        PERMISSION_CAREGIVER_REPORT_CONFIRM,
        PERMISSION_OBSERVATION_CREATE,
        PERMISSION_OBSERVATION_UPDATE,
        PERMISSION_CARE_TASK_UPDATE,
        PERMISSION_COMMUNICATION_CREATE,
        PERMISSION_CARE_GOAL_CREATE,
    }
)

NURSE_PERMISSIONS = _PATIENT_SCOPED_READS | frozenset(
    {
        PERMISSION_CAREGIVER_REPORT_CREATE,
        PERMISSION_CAREGIVER_REPORT_CONFIRM,
        PERMISSION_PATIENT_UPDATE,
        PERMISSION_OBSERVATION_CREATE,
        PERMISSION_OBSERVATION_UPDATE,
        PERMISSION_VISIT_CREATE,
        PERMISSION_VISIT_UPDATE,
        PERMISSION_CARE_TASK_CREATE,
        PERMISSION_CARE_TASK_UPDATE,
        PERMISSION_COMMUNICATION_CREATE,
        PERMISSION_CARE_GOAL_CREATE,
        PERMISSION_ALERT_UPDATE,
    }
)

DOCTOR_PERMISSIONS = _PATIENT_SCOPED_READS | frozenset(
    {
        PERMISSION_CAREGIVER_REPORT_CREATE,
        PERMISSION_CAREGIVER_REPORT_CONFIRM,
        PERMISSION_PATIENT_UPDATE,
        PERMISSION_OBSERVATION_CREATE,
        PERMISSION_OBSERVATION_UPDATE,
        PERMISSION_VISIT_CREATE,
        PERMISSION_VISIT_UPDATE,
        PERMISSION_CARE_TASK_CREATE,
        PERMISSION_CARE_TASK_UPDATE,
        PERMISSION_CARE_PLAN_CREATE,
        PERMISSION_CARE_PLAN_UPDATE,
        PERMISSION_CARE_GOAL_CREATE,
        PERMISSION_CARE_GOAL_UPDATE,
        PERMISSION_ALERT_UPDATE,
    }
)

CARE_COORDINATOR_PERMISSIONS = NURSE_PERMISSIONS | frozenset(
    {
        PERMISSION_PATIENT_CREATE,
        PERMISSION_CAREGIVER_READ,
        PERMISSION_CAREGIVER_CREATE,
        PERMISSION_CAREGIVER_UPDATE,
        PERMISSION_CARE_TEAM_READ,
        PERMISSION_CARE_TEAM_UPDATE,
        PERMISSION_CARE_TASK_ASSIGN,
        PERMISSION_CARE_PLAN_CREATE,
        PERMISSION_CARE_PLAN_UPDATE,
        PERMISSION_CARE_GOAL_UPDATE,
        PERMISSION_USERS_CREATE,
        PERMISSION_USERS_UPDATE,
        PERMISSION_CONSENT_CREATE,
        PERMISSION_CONSENT_UPDATE,
        PERMISSION_ATTACHMENT_CREATE,
    }
)

ADMIN_PERMISSIONS = ALL_PERMISSIONS

ROLE_PERMISSIONS: dict[UserRole, frozenset[str]] = {
    UserRole.PATIENT: PATIENT_PERMISSIONS,
    UserRole.CAREGIVER: CAREGIVER_PERMISSIONS,
    UserRole.NURSE: NURSE_PERMISSIONS,
    UserRole.DOCTOR: DOCTOR_PERMISSIONS,
    UserRole.CARE_COORDINATOR: CARE_COORDINATOR_PERMISSIONS,
    UserRole.ADMIN: ADMIN_PERMISSIONS,
}


def permissions_for_role(role: UserRole) -> frozenset[str]:
    return ROLE_PERMISSIONS.get(role, frozenset())
